version: '3.7'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - PGID=1000
    ports:
    - 7878:7878
    volumes:
    - /opt/radarr/config:/config
    - /media/movies:/movies
    - /media/torrents/output:/downloads
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: bridge
    volumes:
    - /opt/sonarr/config:/config
    - /media/torrents/output:/downloads
    - /media/series:/tv
    - /media/anime:/anime
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - GPID=1000
    ports:
    - 8989:8989
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - PGID=1000
    ports:
    - 9117:9117
    volumes:
    - /opt/jackett/config:/config
    - /media/torrents/output:/downloads
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - VERSION=latest
    - HOSTNAME="Shinryu"
    - PUID=1000
    - PGID=1000
    ports:
    - 32400:32400
    - 32400:32400/udp
    - 32469:32469
    - 32469:32469/udp
    - 5353:5353/udp
    - 1900:1900/udp
    volumes:
    - /media/movies:/data/movies
    - /media/series:/data/tvshows
    - /media/anime:/data/anime
    - /opt/plex/transcode:/data/transcode
    - /opt/plex/config:/config
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - PGID=1000
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    volumes:
    - /media/torrents/output/:/downloads
    - /opt/transmission/config:/config
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - PGID=1000
    ports:
    - 8686:8686
    volumes:
    - /opt/lidarr/config:/config
    - /media/torrents/output/:/downloads
    - /media/music:/music
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - GPID=1000
    ports:
    - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/portainer/data:/data
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=Europe/Brussels
    - PUID=1000
    - PGID=1000
    ports:
    - 3579:3579
    volumes:
    - /opt/ombi/config:/config
